
name: "update pins"

on:
  workflow_dispatch:
  schedule:
    - cron: '25 4,16 * * *'

jobs:
  update_pins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - run: pip install pip-tools==6.9.0
      - run: pip-compile --upgrade --allow-unsafe --generate-hashes pins/requirements.in -o pins/requirements-3.7.txt

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: pip install pip-tools==6.9.0
      - run: pip-compile --upgrade --allow-unsafe --generate-hashes pins/requirements.in -o pins/requirements-3.8.txt

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install pip-tools==6.9.0
      - run: pip-compile --upgrade --allow-unsafe --generate-hashes pins/requirements.in -o pins/requirements-3.9.txt

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pip-tools==6.9.0
      - run: pip-compile --upgrade --allow-unsafe --generate-hashes pins/requirements.in -o pins/requirements-3.10.txt

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install pip-tools==6.9.0
      - run: pip-compile --upgrade --allow-unsafe --generate-hashes pins/requirements.in -o pins/requirements-3.11.txt

      - id: commit
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "install-pinned bot"
            git config --global user.email "install-pinned@users.noreply.github.com"
            git add --all
            ver=$(curl -Ls https://pypi.org/pypi/poetry/json | jq -r .info.version)
            git commit -m "update pins (poetry $ver)"
            commit=$(git rev-parse HEAD)
            sed -i -E "s/@[0-9a-f]{40}.*/@$commit  # $ver/g" README.md
            git commit -am "update README.md (poetry $ver)"
            git push
          fi
